[package]
name = "papers"
version = "0.2.0"
authors = [
    "Peter Gundel <peter.gundel@store2be.com",
    "Fausto Núñez Alberro <fausto.nunez@store2be.com>",
    "Tom Houlé <tom.houle@store2be.com>",
]

[dependencies]
chrono = "*"
dotenv = "*"
error-chain = "0.11.0-rc.2"
futures = "*"
futures-cpupool = "*"
log = "*"
mktemp = "*"
lazy_static = "*"
mime = "*"
quickcheck = "*"
hyper = "^0.11"
hyper-tls = "*"
regex = "*"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
sloggers = "^0.2"
rusoto_core = { git = "https://github.com/store2be/rusoto", branch = "presigned-url" }
rusoto_s3 = { git = "https://github.com/store2be/rusoto", branch = "presigned-url" }
tar = "*"
tera = "*"
tokio-core = "*"
tokio-io = "*"
tokio-process = "*"

[dependencies.slog]
version = "^2"
default-features = false
features = ["max_level_debug", "release_max_level_debug"]

[[bin]]
name = "papers-server"
path = "./src/main.rs"
test = false

[[bin]]
name = "papers-local"
path = "./src/local_server.rs"
test = false
