[package]
name = "papers"
version = "0.1.0"
authors = [
    "Peter Gundel <peter.gundel@store2be.com",
    "Fausto Núñez Alberro <fausto.nunez@store2be.com>",
    "Tom Houlé <tom.houle@store2be.com>",
]

[dependencies]
chrono = "*"
error-chain = "*"
futures = "*"
log = "*"
mktemp = "*"
mime = "*"
multipart = "*"
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slog-term = "1.5.0"
tera = "*"
tokio-core = "*"
tokio-io = "*"
tokio-process = "*"

[dependencies.slog]
version = "1.5.0"
default-features = false
features = ["max_level_debug", "release_max_level_debug"]

[[bin]]
name = "papers-server"
path = "./src/main.rs"
test = false

[[bin]]
name = "papers-local"
path = "./src/local_server.rs"
test = false
